### ISSUE TITLE
Empty materials.json crash the game

### ISSUE THREAD

**Issue by Drakray** [DoubleDoorDevelopment/D3Core#14]
http://pastebin.com/0c3cLvxk

**Comment by dries007** [comment]
Empty file or empty map or empty entries in the map?

**Comment by Drakray** [comment]
empty file, sorry
it do not crash if the file contain`{}`, but crash if totally empty(probably a json thing i was not aware of)

**Comment by dries007** [comment]
Yea, empty string is not a valid map, which is what it looks for.

Op 17 aug. 2016 7:15 p.m. schreef "Raymond Tremblay" <
notifications@github.com>:

**Comment by Drakray** [comment]
not an issue than, I'm just stootip XD
