### ISSUE TITLE
Lilypad Generation Doesn't Seem To Work

### ISSUE THREAD

**Issue by Banjooie** [DoubleDoorDevelopment/D3Core#17]
The D3 Core config that generates a lilypad upon spawn if the player is underwater doesn't seem to function at all? I cannot remotely figure out how to make this work.

**Comment by Claycorp** [comment]
Hmm. Its likely broken if you have it set to true and it's not spawning a pad. It's either on or off nothing special to say or do.

**Comment by Banjooie** [comment]
Does it only work in the ocean biome?

**Comment by Claycorp** [comment]
Nope, all water.

**Comment by Banjooie** [comment]
Then I have no idea.

**Comment by dries007** [comment]
Can you post versions and your config please?

**Comment by Banjooie** [comment]
Version: D3Core-1.9.4-1.3.0.59
Config: http://pastebin.com/CKhf9GFQ

Entire modlist is:
 Astral Sorcery 1.1.2
BetterQuesting-2.3.222 (StandardExpansion 2.3.128
BiomeTweaker-1.10.2-2.1.230
BQAutoreload-1.4.0
D3Core-1.9.4-1.3.0.59
jei 1.10.2 1.3.0.59
OceanFloor 1.10.2 1.0.1
Terrain Crystals 1.10.2 - 1.2.3.jar
