### ISSUE TITLE
Compatibility bug: SparkHammer

### ISSUE THREAD

**Issue by drakray** [DoubleDoorDevelopment/D3Core#21]
Using SparkHammer with D3Core(and Lumberjack) make some Hammer crash in anvil, and some Lumberaxe and Hammer to randomly become unavailable

Related [crash here](https://github.com/thebrightspark/SparksHammers/issues/15)

**Comment by dries007** [comment]
More then likely this line need an extra null check.

https://github.com/DoubleDoorDevelopment/D3Core/blob/5503e612356156d4a17f4eb02f39c60239e1e023/src/main/java/net/doubledoordev/d3core/util/Materials.java#L109

I'll look at it properly when I'm home though.

**Comment by drakray** [comment]
From my log, seems like SH use a HammerMaterial format for their stuff, no underscore

**Comment by dries007** [comment]
Likely irrelevant, the issue seems to be that sometimes the repairmaterial stack gets set to null, which is no longer a valid stack for inventories (although none said it can't be for repair materials, but I'll go with them on this.)

**Comment by dries007** [comment]
@drakray Would you mind testing the latest build?
https://jenkins.dries007.net/job/D3Core/

**Comment by drakray** [comment]
Could start, I got a Missing dependency Forge: any, using Forge 2255

**Comment by drakray** [comment]
just some weird stuff caused by "dynamic create lumberaxe", because some mod set weird repair material, like ironBlock for GiantHammer, dirt?, stair or nether star??, I dont know which mod does that, but it's weird lol
Either way, the SparkHammer compat bug seems fixed

**Comment by drakray** [comment]
in my materials.json, I just make 3 for Botania, and all FunOres because they don't add tools, so they don't set materials, and I like having Osmium tool(sooo durable :D )

**Comment by Claycorp** [comment]
Check the latest log. It should spit out a message with all the information.

**Comment by drakray** [comment]
I found it, just had to search for FATAL and I found it quickly lol
