### ISSUE TITLE
crash from core when using bqm

### ISSUE THREAD

**Issue by SDUBZ** [DoubleDoorDevelopment/D3Core#22]
forge: 1.11.2-2259
D3 core: D3Core-1.11.2-1.3.0.65
lumber axe: Lumberjack-1.11.2-1.3.1.48
bqm: BetterQuesting-2.4.226
crash report:
[crash-2017-03-24_03.35.13-client.txt](https://github.com/DoubleDoorDevelopment/D3Core/files/865461/crash-2017-03-24_03.35.13-client.txt)

**Comment by dries007** [comment]
What inventory, and if you can tell me what the stack is that hover crashes, that would be amazing.

**Comment by dries007** [comment]
Can you test and let us know? It will be uploaded to curseforge then.

**Comment by SDUBZ** [comment]
seems to be fixed now thank you :D
