### ISSUE TITLE
Client crashing on load

### ISSUE THREAD

**Issue by Shahelion** [DoubleDoorDevelopment/D3Core#24]
Nothing has changed, this just suddenly started happening.

https://hastebin.com/javibowavu.md

**Comment by Claycorp** [comment]
In the D3Core config folder there should be two files Groups.json and Players.json
Delete both of them and it should fix it.

**Comment by Claycorp** [comment]
If you delete the "Players.json" and "Groups.json" in the D3core config folder it should fix it.
