### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Obelisk429** [DoubleDoorDevelopment/D3Core#6]
Server running Agrarian Skies 2 modpack http://pastebin.com/icbUxZMD

In the Console right before it output the error it said:
[21:41:21] [Server thread/ERROR] [FML]: The following problems were captured dur
ing this phase
[21:41:21] [Server thread/ERROR] [FML]: Caught exception from D3Core
java.lang.NullPointerException et cetera et cetera

**Comment by Obelisk429** [comment]
Something was weird b/c doing a clean install of the pack fixed it, sorry.

**Comment by Claycorp** [comment]
Not a problem! Let us know if any other issues pop up!
